version: '3.8'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      # 애플리케이션에서 DB에 접근할 때 사용할 URL (db 서비스 이름 사용)
      SPRING_DATASOURCE_URL:  ${DB_URL}
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
    restart: always
  db:
    image: mysql:latest
    container_name: server-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      # 프로젝트 루트의 db 폴더를 MySQL 데이터 디렉토리에 마운트
      - ./db:/var/lib/mysql
