version: '3.8'
services:
  app:
    image: younghak9905/link2trip:${TAG}
    ports:
      - "8080:8080"
    environment:
      # 애플리케이션에서 DB에 접근할 때 사용할 URL (db 서비스 이름 사용)
      SPRING_DATASOURCE_URL:  ${DB_URL}
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
    restart: always
