version: '3.8'
services:
  app:
    image: younghak9905/link2trip:${TAG}
    ports:
      - "8080:8080"
    environment:
      - DB_URL=$DB_URL
      - DB_USERNAME=$DB_USERNAME
      - DB_PASSWORD=$DB_PASSWORD
      - KAKAO_API_KEY=$KAKAO_API_KEY
      - AI_SERVER_URL=$AI_SERVER_URL
    restart: always
