spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false
  cloud:
    config:
      enabled: false
    import-check:
      enabled: false

  server:
    port: 8080

  kakao:
    api:
      key: ${KAKAO_API_KEY}
    redirect:
      url: ${KAKAO_REDIRECT_URL}
springdoc:
  api-docs:
    path: /api-docs
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha
    path: /swagger-ui.html
    disable-swagger-default-url: true
    display-query-params-without-oauth2: true
    doc-expansion: none
  paths-to-match:
    - /api/**
swagger:
  url: {SWAGGER_URL}
ai:
  server:
    url: ${AI_SERVER_URL}