name: CI/CD Pipeline

on:
  push:
    branches: [ "master" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push Docker image
        run: |
          echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/Link2Trip:${{ github.sha }} .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/Link2Trip:${{ github.sha }}

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Connect to EC2 and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/BE
            docker-compose down
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/Link2Trip:${{ github.sha }}
            sed -i 's|image: .*|image: ${{ secrets.DOCKERHUB_USERNAME }}/Link2Trip:${{ github.sha }}|' docker-compose.yml
            docker-compose up -d
